#include "config.h"
#include "HID-Project.h"

#define Alt_r 4
#define Ctrl_r 3
#define Shift_r 2

KeyboardKeycode KeyMap[1][MATRIX_ROWS][MATRIX_COLS]=
{
    {
        {KEY_ESC,KEY_TILDE,KEY_1,KEY_2,KEY_3,KEY_4,KEY_5,KEY_6,KEY_7,KEY_8,KEY_9,KEY_0,KEY_MINUS,KEY_BACKSPACE},
        {KEY_TAB,KEY_Q,KEY_W,KEY_E,KEY_R,KEY_T,KEY_UNDO,KEY_UNDO,KEY_Y,KEY_U,KEY_I,KEY_O,KEY_P,KEY_LEFT_BRACE},
        {KEY_CAPS_LOCK,KEY_A,KEY_S,KEY_D,KEY_F,KEY_G,KEY_UNDO,KEY_UNDO,KEY_H,KEY_J,KEY_K,KEY_L,KEY_SEMICOLON,KEY_ENTER},
        {KEY_LEFT_SHIFT,KEY_Z,KEY_X,KEY_C,KEY_V,KEY_B,KEY_UNDO,KEY_UNDO,KEY_N,KEY_M,KEY_COMMA,KEY_UP,KEYPAD_DOT,KEY_RIGHT_SHIFT},
        {KEY_LEFT_CTRL,KEY_LEFT_WINDOWS,KEY_LEFT_ALT,KEY_BACKSLASH,KEY_QUOTE,KEY_UNDO,KEY_UNDO,KEY_UNDO,KEY_UNDO,KEY_DELETE,KEY_LEFT,KEY_DOWN,KEY_RIGHT,KEY_BACKSPACE},
        {KEY_UNDO,KEY_1,KEY_ENTER,KEY_SPACE,KEY_VOLUME_DOWN,KEY_VOLUME_MUTE,KEY_VOLUME_UP,KEY_PAGE_UP,KEY_PAGE_DOWN,KEY_PAUSE,KEY_SPACE,KEY_PRINTSCREEN,KEY_TILDE,KEY_UNDO},
    }
};